using System.ComponentModel;

namespace PeerXChange.Common;

public enum Language
{
    [Description("Afrikaans")] AF = 1,
    [Description("Albanian")] AL = 2,
    [Description("Arabic")] AR = 3,
    [Description("Armenian")] AM = 4,
    [Description("Azerbaijani")] AZ = 5,
    [Description("Basque")] EU = 6,
    [Description("Bengali")] BN = 7,
    [Description("Bosnian")] BS = 8,
    [Description("Bulgarian")] BG = 9,
    [Description("Catalan")] CA = 10,
    [Description("Chinese")] ZH = 11,
    [Description("Croatian")] HR = 12,
    [Description("Czech")] CS = 13,
    [Description("Danish")] DA = 14,
    [Description("Dutch")] NL = 15,
    [Description("English")] EN = 16,
    [Description("Estonian")] ET = 17,
    [Description("Finnish")] FI = 18,
    [Description("French")] FR = 19,
    [Description("Georgian")] KA = 20,
    [Description("German")] DE = 21,
    [Description("Greek")] EL = 22,
    [Description("Hebrew")] HE = 23,
    [Description("Hindi")] HI = 24,
    [Description("Hungarian")] HU = 25,
    [Description("Icelandic")] IS = 26,
    [Description("Indonesian")] ID = 27,
    [Description("Irish")] GA = 28,
    [Description("Italian")] IT = 29,
    [Description("Japanese")] JA = 30,
    [Description("Kazakh")] KK = 31,
    [Description("Korean")] KO = 32,
    [Description("Kurdish")] KUR = 33,
    [Description("Latin")] LA = 34,
    [Description("Latvian")] LV = 35,
    [Description("Lithuanian")] LT = 36,
    [Description("Macedonian")] MK = 37,
    [Description("Malay")] MS = 38,
    [Description("Maltese")] MT = 39,
    [Description("Mongolian")] MN = 40,
    [Description("Montenegrin")] MNE = 41,
    [Description("Norwegian")] NO = 42,
    [Description("Persian")] FA = 43,
    [Description("Polish")] PL = 44,
    [Description("Portuguese")] PT = 45,
    [Description("Romanian")] RO = 46,
    [Description("Russian")] RU = 47,
    [Description("Scottish Gaelic")] GD = 48,
    [Description("Serbian")] SR = 49,
    [Description("Slovak")] SK = 50,
    [Description("Slovenian")] SL = 51,
    [Description("Spanish")] ES = 52,
    [Description("Swahili")] SW = 53,
    [Description("Swedish")] SV = 54,
    [Description("Tamil")] TA = 55,
    [Description("Thai")] TH = 56,
    [Description("Turkish")] TR = 57,
    [Description("Ukrainian")] UK = 58,
    [Description("Urdu")] UR = 59,
    [Description("Vietnamese")] VI = 60,
    [Description("Welsh")] CY = 61,
    [Description("Yiddish")] YI = 62,
    [Description("Zulu")] ZU = 63
}